{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-strex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/strex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/strex/strex_{{ version }}.tar.gz
  sha256: e962ca3b8a939ef27349ab215d9c7b6bcae1d69b73196b227813eb6b39beb3b3

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate >=1.9.3
    - r-magrittr >=1.5
    - r-purrr
    - r-rlang >=0.3.3
    - r-stringi >=1.7.8
    - r-stringr >=1.5
  run:
    - r-base
    - r-checkmate >=1.9.3
    - r-magrittr >=1.5
    - r-purrr
    - r-rlang >=0.3.3
    - r-stringi >=1.7.8
    - r-stringr >=1.5

test:
  commands:
    - $R -e "library('strex')"           # [not win]
    - "\"%R%\" -e \"library('strex')\""  # [win]

about:
  home: https://rorynolan.github.io/strex
  dev_url: https://github.com/rorynolan/strex
  doc_url: https://rorynolan.github.io/strex/reference/index.html
  license: GPL-3.0-only
  summary: "There are some things that I wish were easier with the 'stringr' or 'stringi' packages. The foremost of these is the extraction of numbers from strings. 'stringr' and 'stringi' make you figure out the regular expression for yourself; 'strex' takes care of this for you. There are many other handy functionalities
    in 'strex'. Contributions to this package are encouraged: it is intended as a miscellany of string manipulation functions that cannot be found in 'stringi' or 'stringr'."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
