{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-strex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/strex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/strex/strex_{{ version }}.tar.gz
  sha256: 103a4a8ec1c85f918837ff175b9bb0e1b1ae17e13df14c4e13eeee7791bbcf52

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate >=1.9.3
    - r-magrittr >=1.5
    - r-rlang >=0.3.3
    - r-stringi >=1.5
    - r-stringr >=1.2.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-checkmate >=1.9.3
    - r-magrittr >=1.5
    - r-rlang >=0.3.3
    - r-stringi >=1.5
    - r-stringr >=1.2.0

test:
  commands:
    - $R -e "library('strex')"           # [not win]
    - "\"%R%\" -e \"library('strex')\""  # [win]

about:
  home: https://rorynolan.github.io/strex, https://github.com/rorynolan/strex
  license: GPL-3.0-only
  summary: "There are some things that I wish were easier with the 'stringr' or 'stringi' packages. The foremost of these is the extraction of numbers from strings. 'stringr' and 'stringi' make you figure out the regular expression for yourself; 'strex' takes care of this for you. There are many other handy functionalities\
    \ in 'strex'. Contributions to this package are encouraged: it is intended as a miscellany of string manipulation functions that cannot be found in 'stringi' or 'stringr'."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: strex
# Title: Extra String Manipulation Functions
# Version: 1.2.0
# Authors@R:  person(given = "Rory", family = "Nolan", role = c("aut", "cre"), email = "rorynoolan@gmail.com", comment = c(ORCID = "0000-0002-5239-4043"))
# Description: There are some things that I wish were easier with the 'stringr' or 'stringi' packages. The foremost of these is the extraction of numbers from strings. 'stringr' and 'stringi' make you figure out the regular expression for yourself; 'strex' takes care of this for you. There are many other handy functionalities in 'strex'. Contributions to this package are encouraged: it is intended as a miscellany of string manipulation functions that cannot be found in 'stringi' or 'stringr'.
# License: GPL-3
# URL: https://rorynolan.github.io/strex, https://github.com/rorynolan/strex
# BugReports: https://github.com/rorynolan/strex/issues
# Depends: R (>= 3.1), stringr (>= 1.2.0)
# Imports: checkmate (>= 1.9.3), glue (>= 1.3.0), magrittr (>= 1.5), matrixStats (>= 0.50.0), ore (>= 1.4.0), processx (>= 3.3.1), Rcpp (>= 1.0.1), rlang (>= 0.3.3), stats, stringi (>= 1.3.1), tibble (>= 2.0.1)
# Suggests: covr, knitr, pacman, purrr, rmarkdown, spelling, testthat (>= 2.1.0)
# LinkingTo: Rcpp (>= 1.0.1)
# VignetteBuilder: knitr
# Biarch: TRUE
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1
# SystemRequirements: C++11
# NeedsCompilation: yes
# Packaged: 2019-09-12 14:47:17 UTC; rnolan
# Author: Rory Nolan [aut, cre] (<https://orcid.org/0000-0002-5239-4043>)
# Maintainer: Rory Nolan <rorynoolan@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-13 04:50:02 UTC
