{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-strex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/strex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/strex/strex_{{ version }}.tar.gz
  sha256: af8740c03cdaf90223564ea000e6ea47503c0faa911109629e6d6538224b7217

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0.1
    - r-checkmate >=1.9.1
    - r-glue >=1.3.0
    - r-magrittr >=1.5
    - r-matrixstats >=0.50.0
    - r-ore >=1.4.0
    - r-rlang >=0.3.3
    - r-stringi
    - r-stringr
    - r-tibble >=2.0.1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=1.0.1
    - r-checkmate >=1.9.1
    - r-glue >=1.3.0
    - r-magrittr >=1.5
    - r-matrixstats >=0.50.0
    - r-ore >=1.4.0
    - r-rlang >=0.3.3
    - r-stringi
    - r-stringr
    - r-tibble >=2.0.1

test:
  commands:
    - $R -e "library('strex')"           # [not win]
    - "\"%R%\" -e \"library('strex')\""  # [win]

about:
  home: https://rorynolan.github.io/strex/
  license: GPL-3
  summary: 'There are some things that I wish were easier with the ''stringr''  or ''stringi''
    packages. The foremost of these is the extraction of numbers  from strings. ''stringr''
    and ''stringi'' make you figure out the regular  expression for yourself; ''strex''
    takes care of this for you. There are many  other handy functionalities in ''strex''.
    Contributions to this package are  encouraged: it is intended as a miscellany of
    string manipulation functions  that cannot be found in ''stringi'' or ''stringr''.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: strex
# Title: Extra String Manipulation Functions
# Version: 1.0.0
# Authors@R: person("Rory", "Nolan", email = "rorynoolan@gmail.com",  role = c("aut", "cre"),  comment = c(ORCID = "0000-0002-5239-4043"))
# Description: There are some things that I wish were easier with the 'stringr'  or 'stringi' packages. The foremost of these is the extraction of numbers  from strings. 'stringr' and 'stringi' make you figure out the regular  expression for yourself; 'strex' takes care of this for you. There are many  other handy functionalities in 'strex'. Contributions to this package are  encouraged: it is intended as a miscellany of string manipulation functions  that cannot be found in 'stringi' or 'stringr'.
# Depends: R (>= 3.1), stringr
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# LinkingTo: Rcpp (>= 1.0.1)
# Imports: Rcpp (>= 1.0.1), magrittr (>= 1.5), checkmate (>= 1.9.1), matrixStats (>= 0.50.0), ore (>= 1.4.0), rlang (>= 0.3.3), tibble (>= 2.0.1), glue (>= 1.3.0), stringi
# RoxygenNote: 6.1.1
# Suggests: testthat (>= 2.1.0), knitr, rmarkdown, pacman, covr, spelling
# SystemRequirements: C++11
# VignetteBuilder: knitr
# URL: https://rorynolan.github.io/strex/
# BugReports: https://github.com/rorynolan/strex/issues
# Language: en-US
# NeedsCompilation: yes
# Packaged: 2019-05-04 11:06:22 UTC; rnolan
# Author: Rory Nolan [aut, cre] (<https://orcid.org/0000-0002-5239-4043>)
# Maintainer: Rory Nolan <rorynoolan@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-05-04 14:30:03 UTC
