# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qA+DM52vpw9VEPEdeNw99sbm1xHm0PThHyNMYjEVWzO2CDW83kW8C7WX5LrELbtcS+BKE7v0ODfRVHp6i9r2u5UZXQ9gQamctfR6Xu8NqIRLfrOyx2SaD3lNOv4Nz7G4i8ENv4O00JnK+C+sonhQx7l4IqcHf7veP2HKXoJuAY7NF0BGMoMifwzndyXWmDX2YOcDYZ1+1LYZtbANNN+cZTALzUWt3myX28EKMD3rdpwFsl3ryV6RJhJm+IpgK+bBzmdiBfpd78Wwh3edp+aMg0WILTdoG1yOKERn+EKe/9juPBYK2384Me0VhA8ku73xQaojmUVIGktkQ0DakJ384+224h6PeO5gNufs6qC0uAFz5gdxUeSvEs2yrhw+iWnSk1SRTiefQnCmmdGKc0jnJpSkYlCV2CmyKY3bkydvEjvB18J6FyOE0loX4CNswbJsQitgDpk65WILZ7AnYq1XrYu29S6ndZjqPu0QhksCM7rNGjr0Lp4qQpnIzV9alV6phNFl8F1P7bg2/97Et7DuGLooeEWTcovRXqnHcGwfXPIz49OBOy8aVtypSw3G8/oUU+6tEq2UDBcJDIZhV4nNa1JVinn5sK1tYMYjma8SuoSuvfXthQWQb6/3HtIvazQ5ozx8XsKeFM1w6k4TiY8SUqkBlNYvZ+ioNREbj+3Oy3U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml