travis:
  secure:
    BINSTAR_TOKEN: PxBT4+hT10iyU4TjJT0nSe8RM4/9hwANKCLEZBemjfBHSHuW3voTCeQbkOdC3UIpOeiagZxVFHwHfBAKepGatbx3PYAy2UCbAk3HQbvHxMOxcE1g3xy/myFRTm+kIGwnsYsO3xW9XSaI2GbRVEqD7jRlIFkXHhg3oEs0OSuVkcAcK/jXz3MebccRcroiJq+e/rOn1/a/zX9CoQIcSNOu6J2Mzh3mXRAJtN2tkDy1bEH5fbPqgmXiV4QpLMZOjxQ4D+xrTfOHFAXxsSH1ch7xh51Z/ehOXBNDZ8mvIDIQtRH2gh/tIGIKAUPfYa9NTV2QCXv11vjqykNCgHBfS0+muR1/Uj4Bx+Kt8UNp3cQAd0Y3b/EKZ3l7OGlBG1HdHv4ziq/pC0NEIsqPPRjjAwQgSeMoNIzCEilW8UKS8rOfardXY0aptJoWofkmYjZgZU/a0LZ1O0DJIWlUBK13ziTfNHWPxmEEyVINLHNU+jwC4DcZZ9GZU1kEanQxmfcaM2UguxzzlsOgzTs3XZqbtRYI1poD19YDwDoj4iN4chaRL79CXN65hh8UBAiQH9TU4NWuusDBSg3DHEa4VvL8Pro5WMH4WjcyqEHAMU8wxXQ2FkWD0qAoiIICUQIT/qrCHPI+wY0AinGQ5Ay+v0b6h7khiZbEmK13BCjsGWxx4reZr/4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
