appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: qA+DM52vpw9VEPEdeNw99sbm1xHm0PThHyNMYjEVWzO2CDW83kW8C7WX5LrELbtcS+BKE7v0ODfRVHp6i9r2u5UZXQ9gQamctfR6Xu8NqIRLfrOyx2SaD3lNOv4Nz7G4i8ENv4O00JnK+C+sonhQx7l4IqcHf7veP2HKXoJuAY7NF0BGMoMifwzndyXWmDX2YOcDYZ1+1LYZtbANNN+cZTALzUWt3myX28EKMD3rdpwFsl3ryV6RJhJm+IpgK+bBzmdiBfpd78Wwh3edp+aMg0WILTdoG1yOKERn+EKe/9juPBYK2384Me0VhA8ku73xQaojmUVIGktkQ0DakJ384+224h6PeO5gNufs6qC0uAFz5gdxUeSvEs2yrhw+iWnSk1SRTiefQnCmmdGKc0jnJpSkYlCV2CmyKY3bkydvEjvB18J6FyOE0loX4CNswbJsQitgDpk65WILZ7AnYq1XrYu29S6ndZjqPu0QhksCM7rNGjr0Lp4qQpnIzV9alV6phNFl8F1P7bg2/97Et7DuGLooeEWTcovRXqnHcGwfXPIz49OBOy8aVtypSw3G8/oUU+6tEq2UDBcJDIZhV4nNa1JVinn5sK1tYMYjma8SuoSuvfXthQWQb6/3HtIvazQ5ozx8XsKeFM1w6k4TiY8SUqkBlNYvZ+ioNREbj+3Oy3U=
conda_forge_output_validation: true
